[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_amm_2023 = "GiVFHELhmrVa7sMGZUcG52M3rfqzPXNsZ9AokuKD8Tmy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/elon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
